#!/usr/bin/env bash
# Get information about the "holbertonschool" file

exists=0

if [ -e "holbertonschool" ]; then
    echo "holbertonschool file exists"

    if [ -s "holbertonschool" ]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi

    if [ -f "holbertonschool" ]; then
	echo "holbertonschool file is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
